# Copyright (c) 2022 Unately
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: build installers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - installers/**

jobs:
  push:
    name: "gears:${{ matrix.oses }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        oses:
          - alpine
          - debian
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,amd64
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: jqcr.gq
          username: ${{ secrets.JQCR_USER }}
          password: ${{ secrets.JQCR_PASSWORD }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./installers
          file: ./installers/${{ matrix.oses }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/upackages/gears:installer_${{ matrix.oses }}
            jqcr.gq/gears/installers:${{ matrix.oses }}
